name: Compile Notes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full python3 python3-pip
        pip3 install -r requirements.txt || true  # If a requirements.txt exists for Python dependencies

    - name: Compile PDF
      run: make all

    - name: Upload Compiled PDF
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdf
        path: |
          top.pdf
          chapter_pdfs/
